export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const UNSUCCESSFUL_REGISTRATION = 'UNSUCCESSFUL_REGISTRATION';


export const SUCCESSFUL_LOGIN= 'SUCCESSFUL_LOGIN';
export const UNSUCCESSFUL_LOGIN= 'UNSUCCESSFUL_LOGIN';

export const LOGOUT= 'LOGOUT';

export const SHOW_ALERT = 'SHOW_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

export const UPLOADING_FILE = 'UPLOADING_FILE';
export const SUCCESSFUL_UPLOADING= 'SUCCESSFUL_UPLOADING';
export const UNSUCCESSFUL_UPLOADING= 'UNSUCCESSFUL_UPLOADING';


export const SUCCESSFUL_LINK = 'SUCCESSFUL_LINK';
export const UNSUCCESSFUL_LINK = 'UNSUCCESSFUL_LINK';

export const CLEAN_STATE = 'CLEAN_STATE';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const ADD_DOWNLOAD = 'ADD_DOWNLOAD';